- name: Creating user
  ansible.builtin.user:
    name: roboshop
- name: Recursively remove app dir
  ansible.builtin.file:
    path: /app
    state: absent
- name: Creating app dir
  ansible.builtin.file:
    path: /app
    state: directory
- name: "Download {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp
- name: Extracting application
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes